### ISSUE TITLE
Kernel upgrade failed

### ISSUE THREAD

**Issue by zcatav** [SpiralLinux/SpiralLinux-project#299]
Hi there,
I've been using spiral linux trixie for a long time, just testing in the repository. The latest kernel upgrade caused problems. The running kernel is version 6.4.0-2 and the attempted upgrade is version 6.4.0-3. 
Below are the error messages and logs. How can I solve this problem?
Thank you for your attention.

`Setting up linux-headers-6.4.0-3-amd64 (6.4.11-1) ...
/etc/kernel/header_postinst.d/dkms:
dkms: running auto installation service for kernel 6.4.0-3-amd64.
Sign command: /lib/modules/6.4.0-3-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.4.0-3-amd64 -C /lib/modules/6.4.0-3-amd64/build M=/var/lib/dkms/r8168/8.051.02/build........(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.4.0-3-amd64 (x86_64)
Consult /var/lib/dkms/r8168/8.051.02/build/make.log for more information.
dkms autoinstall on 6.4.0-3-amd64/x86_64 succeeded for broadcom-sta
dkms autoinstall on 6.4.0-3-amd64/x86_64 failed for r8168(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.4.0-3-amd64 failed!
run-parts: /etc/kernel/header_postinst.d/dkms exited with return code 11
Failed to process /etc/kernel/header_postinst.d at /var/lib/dpkg/info/linux-headers-6.4.0-3-amd64.postinst line 11.
dpkg: error processing package linux-headers-6.4.0-3-amd64 (--configure):
 installed linux-headers-6.4.0-3-amd64 package post-installation script subprocess returned error exit status 1
Setting up linux-image-6.4.0-3-amd64 (6.4.11-1) ...
/etc/kernel/postinst.d/dkms:
dkms: running auto installation service for kernel 6.4.0-3-amd64.
Sign command: /lib/modules/6.4.0-3-amd64/build/scripts/sign-file
Signing key: /var/lib/dkms/mok.key
Public certificate (MOK): /var/lib/dkms/mok.pub

Building module:
Cleaning build area...
make -j4 KERNELRELEASE=6.4.0-3-amd64 -C /lib/modules/6.4.0-3-amd64/build M=/var/lib/dkms/r8168/8.051.02/build.......(bad exit status: 2)
Error! Bad return status for module build on kernel: 6.4.0-3-amd64 (x86_64)
Consult /var/lib/dkms/r8168/8.051.02/build/make.log for more information.
dkms autoinstall on 6.4.0-3-amd64/x86_64 succeeded for broadcom-sta
dkms autoinstall on 6.4.0-3-amd64/x86_64 failed for r8168(10)
Error! One or more modules failed to install during autoinstall.
Refer to previous errors for more information.
dkms: autoinstall for kernel: 6.4.0-3-amd64 failed!
run-parts: /etc/kernel/postinst.d/dkms exited with return code 11
dpkg: error processing package linux-image-6.4.0-3-amd64 (--configure):
 installed linux-image-6.4.0-3-amd64 package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 linux-headers-6.4.0-3-amd64
 linux-image-6.4.0-3-amd64
Config is in use.
E: Sub-process /usr/bin/dpkg returned an error code (1)

DKMS make.log for r8168-8.051.02 for kernel 6.4.0-3-amd64 (x86_64)
Tue Aug 29 11:17:04 +03 2023
make: Entering directory '/usr/src/linux-headers-6.4.0-3-amd64'
  CC [M]  /var/lib/dkms/r8168/8.051.02/build/r8168_n.o
  CC [M]  /var/lib/dkms/r8168/8.051.02/build/r8168_asf.o
  CC [M]  /var/lib/dkms/r8168/8.051.02/build/rtl_eeprom.o
  CC [M]  /var/lib/dkms/r8168/8.051.02/build/rtltool.o
/var/lib/dkms/r8168/8.051.02/build/r8168_n.c: In function 'r8168_csum_workaround':
/var/lib/dkms/r8168/8.051.02/build/r8168_n.c:29208:24: error: implicit declaration of function 'skb_gso_segment'; did you mean 'skb_gso_reset'? [-Werror=implicit-function-declaration]
29208 |                 segs = skb_gso_segment(skb, features);
      |                        ^~~~~~~~~~~~~~~
      |                        skb_gso_reset
/var/lib/dkms/r8168/8.051.02/build/r8168_n.c:29208:22: warning: assignment to 'struct sk_buff *' from 'int' makes pointer from integer without a cast [-Wint-conversion]
29208 |                 segs = skb_gso_segment(skb, features);
      |                      ^
cc1: some warnings being treated as errors
make[1]: *** [/usr/src/linux-headers-6.4.0-3-common/scripts/Makefile.build:257: /var/lib/dkms/r8168/8.051.02/build/r8168_n.o] Error 1
make: *** [/usr/src/linux-headers-6.4.0-3-common/Makefile:2057: /var/lib/dkms/r8168/8.051.02/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.4.0-3-amd64'

`

**Comment by geckolinux** [comment]
https://github.com/SpiralLinux/SpiralLinux-project/releases/tag/12.231001
